/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => VocalogPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian6 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  audioFolder: "Inbox/Voice",
  outputFolder: "",
  // 空字符串表示使用根目录
  dailyNoteFormat: "YYYY-MM-DD",
  sttApiUrl: "https://api.openai.com/v1/audio/transcriptions",
  sttApiKey: "",
  sttModel: "whisper-1",
  llmApiUrl: "https://api.deepseek.com/v1/chat/completions",
  llmApiKey: "",
  llmModel: "deepseek-chat",
  systemPrompt: `You are an AI assistant helping to organize voice memos into structured daily notes. Your task is to:

1. Analyze all transcribed voice recordings from today
2. Extract key information, events, tasks, and ideas
3. Organize them into a clear, structured summary

Output format:
- Use bullet points for better readability
- Group related items together
- Highlight important tasks with checkboxes [ ]
- Keep the original timestamps for reference
- Preserve the chronological order when relevant

Be concise but comprehensive. Focus on actionable items and important information.`
};
var VocalogSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    containerEl.createEl("h2", { text: "Vocalog Settings" });
    containerEl.createEl("h3", { text: "Basic Settings" });
    new import_obsidian.Setting(containerEl).setName("Audio folder").setDesc("Folder path where audio recordings are stored").addText((text) => text.setPlaceholder("Inbox/Voice").setValue(this.plugin.settings.audioFolder).onChange(async (value) => {
      this.plugin.settings.audioFolder = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Output folder").setDesc("Folder where daily notes will be saved (leave empty for vault root)").addText((text) => text.setPlaceholder("Daily Notes").setValue(this.plugin.settings.outputFolder).onChange(async (value) => {
      this.plugin.settings.outputFolder = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Daily note format").setDesc("Date format for daily notes (using moment.js format)").addText((text) => text.setPlaceholder("YYYY-MM-DD").setValue(this.plugin.settings.dailyNoteFormat).onChange(async (value) => {
      this.plugin.settings.dailyNoteFormat = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "Speech-to-Text (STT) Settings" });
    new import_obsidian.Setting(containerEl).setName("STT API URL").setDesc("API endpoint for speech-to-text service (OpenAI Whisper compatible)").addText((text) => text.setPlaceholder("https://api.openai.com/v1/audio/transcriptions").setValue(this.plugin.settings.sttApiUrl).onChange(async (value) => {
      this.plugin.settings.sttApiUrl = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("STT API Key").setDesc("API key for authentication").addText((text) => {
      text.setPlaceholder("Enter your API key").setValue(this.plugin.settings.sttApiKey).onChange(async (value) => {
        this.plugin.settings.sttApiKey = value;
        await this.plugin.saveSettings();
      });
      text.inputEl.type = "password";
    });
    new import_obsidian.Setting(containerEl).setName("STT Model").setDesc("Model to use for transcription").addText((text) => text.setPlaceholder("whisper-1").setValue(this.plugin.settings.sttModel).onChange(async (value) => {
      this.plugin.settings.sttModel = value;
      await this.plugin.saveSettings();
    }));
    containerEl.createEl("h3", { text: "LLM Summarization Settings" });
    new import_obsidian.Setting(containerEl).setName("LLM API URL").setDesc("API endpoint for LLM service (OpenAI Chat compatible)").addText((text) => text.setPlaceholder("https://api.deepseek.com/v1/chat/completions").setValue(this.plugin.settings.llmApiUrl).onChange(async (value) => {
      this.plugin.settings.llmApiUrl = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("LLM API Key").setDesc("API key for authentication").addText((text) => {
      text.setPlaceholder("Enter your API key").setValue(this.plugin.settings.llmApiKey).onChange(async (value) => {
        this.plugin.settings.llmApiKey = value;
        await this.plugin.saveSettings();
      });
      text.inputEl.type = "password";
    });
    new import_obsidian.Setting(containerEl).setName("LLM Model").setDesc("Model to use for summarization").addText((text) => text.setPlaceholder("deepseek-chat").setValue(this.plugin.settings.llmModel).onChange(async (value) => {
      this.plugin.settings.llmModel = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("System Prompt").setDesc("Prompt to guide the AI in generating summaries").addTextArea((text) => {
      text.setPlaceholder("Enter system prompt").setValue(this.plugin.settings.systemPrompt).onChange(async (value) => {
        this.plugin.settings.systemPrompt = value;
        await this.plugin.saveSettings();
      });
      text.inputEl.rows = 10;
      text.inputEl.cols = 50;
    });
  }
};

// src/fileRetrieval.ts
var import_obsidian2 = require("obsidian");
function getTodayAudioFiles(vault, audioFolder) {
  const todayStart = (0, import_obsidian2.moment)().startOf("day");
  const todayEnd = (0, import_obsidian2.moment)().endOf("day");
  return getAudioFilesByDateRange(vault, audioFolder, todayStart, todayEnd);
}
function getAudioFilesByDateRange(vault, audioFolder, startDate, endDate) {
  const allFiles = vault.getFiles();
  const audioFiles = allFiles.filter((file) => {
    const isInFolder = file.path.startsWith(audioFolder);
    const validExtensions = ["mp3", "m4a", "wav", "webm", "ogg"];
    const ext = file.extension.toLowerCase();
    const isValidExtension = validExtensions.includes(ext);
    const fileTime = (0, import_obsidian2.moment)(file.stat.ctime);
    const isInRange = fileTime.isBetween(startDate, endDate, null, "[]");
    return isInFolder && isValidExtension && isInRange;
  });
  audioFiles.sort((a, b) => a.stat.ctime - b.stat.ctime);
  return audioFiles;
}
function getAudioFilesByDate(vault, audioFolder, date) {
  const dayStart = date.clone().startOf("day");
  const dayEnd = date.clone().endOf("day");
  return getAudioFilesByDateRange(vault, audioFolder, dayStart, dayEnd);
}

// src/transcription.ts
var import_obsidian3 = require("obsidian");
async function transcribeAudio(audioData, fileName, settings) {
  const formData = new FormData();
  const extension = fileName.split(".").pop() || "m4a";
  const blob = new Blob([audioData], { type: `audio/${extension}` });
  formData.append("file", blob, fileName);
  formData.append("model", settings.sttModel);
  try {
    const response = await fetch(settings.sttApiUrl, {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${settings.sttApiKey}`
      },
      body: formData
    });
    if (!response.ok) {
      const errorText = await response.text().catch(() => "Unknown error");
      throw new Error(`STT API failed: ${response.statusText} - ${errorText}`);
    }
    const result = await response.json();
    return result.text;
  } catch (error) {
    if (error.message.includes("Failed to fetch")) {
      throw new Error(`\u7F51\u7EDC\u9519\u8BEF\uFF1A\u65E0\u6CD5\u8FDE\u63A5\u5230 STT API\u3002\u8BF7\u68C0\u67E5\uFF1A
1. API URL \u662F\u5426\u6B63\u786E
2. \u7F51\u7EDC\u8FDE\u63A5\u662F\u5426\u6B63\u5E38
3. \u662F\u5426\u9700\u8981\u4EE3\u7406
\u539F\u59CB\u9519\u8BEF: ${error.message}`);
    }
    throw error;
  }
}
async function transcribeBatch(files, vault, settings, noticeCallback) {
  const results = [];
  for (let i = 0; i < files.length; i++) {
    const file = files[i];
    noticeCallback(`Transcribing ${i + 1}/${files.length}: ${file.name}`);
    try {
      const audioData = await vault.readBinary(file);
      const text = await transcribeAudio(audioData, file.name, settings);
      results.push({
        time: (0, import_obsidian3.moment)(file.stat.ctime).format("HH:mm"),
        text,
        success: true
      });
    } catch (error) {
      console.error(`Failed to transcribe ${file.name}:`, error);
      results.push({
        time: (0, import_obsidian3.moment)(file.stat.ctime).format("HH:mm"),
        text: "[Transcription Failed]",
        success: false
      });
    }
  }
  return results;
}

// src/summarization.ts
async function summarizeTranscripts(transcripts, settings) {
  const context = transcripts.map((t) => `[${t.time}] ${t.text}`).join("\n\n");
  const requestBody = {
    model: settings.llmModel,
    messages: [
      { role: "system", content: settings.systemPrompt },
      { role: "user", content: context }
    ],
    temperature: 0.7
  };
  try {
    const response = await fetch(settings.llmApiUrl, {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${settings.llmApiKey}`,
        "Content-Type": "application/json"
      },
      body: JSON.stringify(requestBody)
    });
    if (!response.ok) {
      const errorText = await response.text().catch(() => "Unknown error");
      throw new Error(`LLM API failed: ${response.statusText} - ${errorText}`);
    }
    const result = await response.json();
    return result.choices[0].message.content;
  } catch (error) {
    if (error.message.includes("Failed to fetch")) {
      throw new Error(`\u7F51\u7EDC\u9519\u8BEF\uFF1A\u65E0\u6CD5\u8FDE\u63A5\u5230 LLM API\u3002\u8BF7\u68C0\u67E5\uFF1A
1. API URL \u662F\u5426\u6B63\u786E
2. API Key \u662F\u5426\u6709\u6548
3. \u7F51\u7EDC\u8FDE\u63A5\u662F\u5426\u6B63\u5E38
\u539F\u59CB\u9519\u8BEF: ${error.message}`);
    }
    throw error;
  }
}

// src/journalWriter.ts
var import_obsidian4 = require("obsidian");
async function writeToJournal(content, settings, vault, targetDate) {
  const dateToUse = targetDate || (0, import_obsidian4.moment)();
  const fileName = dateToUse.format(settings.dailyNoteFormat) + ".md";
  const filePath = settings.outputFolder ? `${settings.outputFolder}/${fileName}` : fileName;
  if (settings.outputFolder) {
    const folderPath = settings.outputFolder;
    const folder = vault.getAbstractFileByPath(folderPath);
    if (!folder) {
      await vault.createFolder(folderPath).catch(() => {
      });
    }
  }
  let dailyNote = vault.getAbstractFileByPath(filePath);
  if (!dailyNote) {
    dailyNote = await vault.create(filePath, "");
  }
  if (!(dailyNote instanceof import_obsidian4.TFile)) {
    throw new Error("Daily note is not a file");
  }
  let existingContent = await vault.read(dailyNote);
  const newContent = existingContent.trimEnd() + "\n\n" + content + "\n";
  await vault.modify(dailyNote, newContent);
}

// src/calendarModal.ts
var import_obsidian5 = require("obsidian");
var CalendarModal = class extends import_obsidian5.Modal {
  constructor(app, onSubmit) {
    super(app);
    this.onSubmit = onSubmit;
    this.selectedDates = /* @__PURE__ */ new Set();
    import_obsidian5.moment.locale("zh-cn");
    this.currentMonth = (0, import_obsidian5.moment)().startOf("month");
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("vocalog-calendar-modal");
    contentEl.createEl("h2", { text: "\u9009\u62E9\u65E5\u671F" });
    this.createMonthNavigation(contentEl);
    this.calendarEl = contentEl.createDiv({ cls: "calendar-container" });
    this.renderCalendar();
    contentEl.createEl("h3", { text: "\u5FEB\u901F\u9009\u62E9" });
    const quickButtons = contentEl.createDiv({ cls: "date-quick-options" });
    const addButton = (text, dates) => {
      const btn = quickButtons.createEl("button", { text });
      btn.onclick = () => {
        dates.forEach((d) => this.selectedDates.add(d));
        this.renderCalendar();
        this.updateGenerateButton();
      };
    };
    addButton("\u4ECA\u5929", [(0, import_obsidian5.moment)().format("YYYY-MM-DD")]);
    addButton("\u6628\u5929", [(0, import_obsidian5.moment)().subtract(1, "day").format("YYYY-MM-DD")]);
    addButton("\u672C\u5468", this.getWeekDates((0, import_obsidian5.moment)()));
    addButton("\u6700\u8FD17\u5929", this.getLast7Days());
    const clearBtn = quickButtons.createEl("button", { text: "\u6E05\u7A7A", cls: "mod-warning" });
    clearBtn.onclick = () => {
      this.selectedDates.clear();
      this.renderCalendar();
      this.updateGenerateButton();
    };
    const buttonContainer = contentEl.createDiv({ cls: "modal-button-container" });
    const generateBtn = buttonContainer.createEl("button", {
      text: `\u751F\u6210 (${this.selectedDates.size})`,
      cls: "mod-cta"
    });
    generateBtn.setAttribute("id", "generate-btn");
    generateBtn.onclick = () => {
      if (this.selectedDates.size === 0) {
        return;
      }
      this.close();
      this.submit();
    };
    const cancelBtn = buttonContainer.createEl("button", { text: "\u53D6\u6D88" });
    cancelBtn.onclick = () => {
      this.close();
    };
  }
  createMonthNavigation(containerEl) {
    const nav = containerEl.createDiv({ cls: "calendar-nav" });
    const prevBtn = nav.createEl("button", { text: "\u25C0 \u4E0A\u6708", cls: "calendar-nav-btn" });
    prevBtn.onclick = () => {
      this.currentMonth.subtract(1, "month");
      this.renderCalendar();
    };
    const monthLabel = nav.createEl("span", {
      text: this.currentMonth.format("YYYY\u5E74 MM\u6708"),
      cls: "calendar-month-label"
    });
    monthLabel.setAttribute("id", "month-label");
    const nextBtn = nav.createEl("button", { text: "\u4E0B\u6708 \u25B6", cls: "calendar-nav-btn" });
    nextBtn.onclick = () => {
      this.currentMonth.add(1, "month");
      this.renderCalendar();
    };
  }
  renderCalendar() {
    this.calendarEl.empty();
    const monthLabel = document.getElementById("month-label");
    if (monthLabel) {
      monthLabel.textContent = this.currentMonth.format("YYYY\u5E74 MM\u6708");
    }
    const weekdays = ["\u65E5", "\u4E00", "\u4E8C", "\u4E09", "\u56DB", "\u4E94", "\u516D"];
    const headerRow = this.calendarEl.createDiv({ cls: "calendar-weekdays" });
    weekdays.forEach((day) => {
      headerRow.createEl("div", { text: day, cls: "calendar-weekday" });
    });
    const daysGrid = this.calendarEl.createDiv({ cls: "calendar-days" });
    const startOfMonth = this.currentMonth.clone().startOf("month");
    const endOfMonth = this.currentMonth.clone().endOf("month");
    const firstDayOfWeek = startOfMonth.day();
    const startDate = startOfMonth.clone().subtract(firstDayOfWeek, "days");
    const lastDayOfWeek = endOfMonth.day();
    const endDate = endOfMonth.clone().add(6 - lastDayOfWeek, "days");
    const today = (0, import_obsidian5.moment)().format("YYYY-MM-DD");
    let currentDate = startDate.clone();
    while (currentDate.isSameOrBefore(endDate, "day")) {
      const dateStr = currentDate.format("YYYY-MM-DD");
      const dayEl = daysGrid.createEl("div", { cls: "calendar-day" });
      if (!currentDate.isSame(this.currentMonth, "month")) {
        dayEl.addClass("other-month");
      }
      if (currentDate.format("YYYY-MM-DD") === today) {
        dayEl.addClass("today");
      }
      if (this.selectedDates.has(dateStr)) {
        dayEl.addClass("selected");
      }
      if (currentDate.isAfter((0, import_obsidian5.moment)(), "day")) {
        dayEl.addClass("future");
      }
      dayEl.createEl("span", { text: currentDate.format("D") });
      dayEl.onclick = () => {
        if (this.selectedDates.has(dateStr)) {
          this.selectedDates.delete(dateStr);
        } else {
          this.selectedDates.add(dateStr);
        }
        this.renderCalendar();
        this.updateGenerateButton();
      };
      currentDate.add(1, "day");
    }
  }
  updateGenerateButton() {
    const btn = document.getElementById("generate-btn");
    if (btn) {
      btn.textContent = `\u751F\u6210 (${this.selectedDates.size})`;
    }
  }
  getWeekDates(date) {
    const dayOfWeek = date.day();
    const start = date.clone().subtract(dayOfWeek, "days");
    const dates = [];
    for (let i = 0; i < 7; i++) {
      dates.push(start.clone().add(i, "days").format("YYYY-MM-DD"));
    }
    return dates;
  }
  getLast7Days() {
    const dates = [];
    for (let i = 0; i < 7; i++) {
      dates.push((0, import_obsidian5.moment)().subtract(i, "days").format("YYYY-MM-DD"));
    }
    return dates;
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
  submit() {
    const dates = Array.from(this.selectedDates).map((d) => (0, import_obsidian5.moment)(d, "YYYY-MM-DD")).sort((a, b) => a.valueOf() - b.valueOf());
    this.onSubmit(dates);
  }
};

// src/main.ts
var VocalogPlugin = class extends import_obsidian6.Plugin {
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new VocalogSettingTab(this.app, this));
    this.addRibbonIcon("microphone", "Vocalog: Generate Audio Notes", async (evt) => {
      await this.generateAudioNotes();
    });
    this.addCommand({
      id: "generate-audio-notes",
      name: "Generate Audio Notes",
      callback: () => this.generateAudioNotes()
    });
    this.addCommand({
      id: "generate-from-selected",
      name: "Generate from Selected Audio Files",
      checkCallback: (checking) => {
        const files = this.getSelectedAudioFiles();
        if (files.length > 0) {
          if (!checking) {
            this.generateFromFiles(files);
          }
          return true;
        }
        return false;
      }
    });
    this.addCommand({
      id: "generate-by-date-range",
      name: "Generate Audio Notes by Date Range",
      callback: () => {
        new CalendarModal(this.app, async (dates) => {
          await this.generateBySelectedDates(dates);
        }).open();
      }
    });
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file) => {
        if (this.isAudioFile(file)) {
          menu.addItem((item) => {
            item.setTitle("\u{1F3A4} Generate Audio Note").setIcon("microphone").onClick(async () => {
              await this.generateFromFiles([file]);
            });
          });
        }
      })
    );
  }
  async generateAudioNotes() {
    const notice = new import_obsidian6.Notice("Starting Vocalog processing...", 0);
    try {
      const files = getTodayAudioFiles(this.app.vault, this.settings.audioFolder);
      if (files.length === 0) {
        notice.hide();
        new import_obsidian6.Notice("No audio recordings found for today.");
        return;
      }
      await this.processAudioFiles(files, notice);
    } catch (error) {
      notice.hide();
      console.error("Vocalog processing failed:", error);
      new import_obsidian6.Notice(`\u274C Error: ${error.message}`);
    }
  }
  async generateFromFiles(files, targetDate) {
    const notice = new import_obsidian6.Notice("Processing selected audio files...", 0);
    try {
      if (files.length === 0) {
        notice.hide();
        new import_obsidian6.Notice("No audio files selected.");
        return;
      }
      files.sort((a, b) => a.stat.ctime - b.stat.ctime);
      await this.processAudioFiles(files, notice, targetDate);
    } catch (error) {
      notice.hide();
      console.error("Audio processing failed:", error);
      new import_obsidian6.Notice(`\u274C Error: ${error.message}`);
    }
  }
  async generateBySelectedDates(dates) {
    const notice = new import_obsidian6.Notice("Processing audio files for selected dates...", 0);
    try {
      if (dates.length === 0) {
        notice.hide();
        new import_obsidian6.Notice("No dates selected.");
        return;
      }
      let totalProcessed = 0;
      for (const date of dates) {
        const files = getAudioFilesByDate(this.app.vault, this.settings.audioFolder, date);
        if (files.length > 0) {
          notice.setMessage(`Processing ${date.format("YYYY-MM-DD")} (${files.length} files)...`);
          await this.processAudioFiles(files, notice, date);
          totalProcessed += files.length;
        }
      }
      notice.hide();
      if (totalProcessed === 0) {
        new import_obsidian6.Notice(`No audio recordings found for selected dates.`);
      } else {
        new import_obsidian6.Notice(`\u2705 Processed ${totalProcessed} audio files from ${dates.length} day(s)!`);
      }
    } catch (error) {
      notice.hide();
      console.error("Selected dates processing failed:", error);
      new import_obsidian6.Notice(`\u274C Error: ${error.message}`);
    }
  }
  async generateByDateRange(startDate, endDate) {
    const notice = new import_obsidian6.Notice("Processing audio files by date range...", 0);
    try {
      if (startDate.isSame(endDate, "day")) {
        const files = getAudioFilesByDate(this.app.vault, this.settings.audioFolder, startDate);
        if (files.length === 0) {
          notice.hide();
          new import_obsidian6.Notice(`No audio recordings found for ${startDate.format("YYYY-MM-DD")}.`);
          return;
        }
        await this.processAudioFiles(files, notice, startDate);
      } else {
        const daysDiff = endDate.diff(startDate, "days") + 1;
        let totalProcessed = 0;
        for (let i = 0; i < daysDiff; i++) {
          const currentDate = startDate.clone().add(i, "days");
          const files = getAudioFilesByDate(this.app.vault, this.settings.audioFolder, currentDate);
          if (files.length > 0) {
            notice.setMessage(`Processing ${currentDate.format("YYYY-MM-DD")} (${files.length} files)...`);
            await this.processAudioFiles(files, notice, currentDate);
            totalProcessed += files.length;
          }
        }
        notice.hide();
        if (totalProcessed === 0) {
          new import_obsidian6.Notice(`No audio recordings found in date range.`);
        } else {
          new import_obsidian6.Notice(`\u2705 Processed ${totalProcessed} audio files from ${daysDiff} days!`);
        }
        return;
      }
    } catch (error) {
      notice.hide();
      console.error("Date range processing failed:", error);
      new import_obsidian6.Notice(`\u274C Error: ${error.message}`);
    }
  }
  async processAudioFiles(files, notice, targetDate) {
    notice.setMessage(`Found ${files.length} audio files. Transcribing...`);
    const transcripts = await transcribeBatch(
      files,
      this.app.vault,
      this.settings,
      (msg) => notice.setMessage(msg)
    );
    notice.setMessage("Generating summary with AI...");
    let finalContent;
    try {
      finalContent = await summarizeTranscripts(transcripts, this.settings);
    } catch (error) {
      console.error("LLM summarization failed:", error);
      finalContent = transcripts.map((t) => `[${t.time}] ${t.text}`).join("\n\n");
      finalContent = "\u26A0\uFE0F AI Summary Failed - Raw Transcripts:\n\n" + finalContent;
    }
    const audioLinks = this.generateAudioLinks(files);
    if (audioLinks) {
      finalContent += "\n\n---\n\n" + audioLinks;
    }
    notice.setMessage("Writing to daily note...");
    await writeToJournal(finalContent, this.settings, this.app.vault, targetDate);
    notice.hide();
    new import_obsidian6.Notice("\u2705 Vocalog generated successfully!");
  }
  generateAudioLinks(files) {
    if (files.length === 0)
      return "";
    const links = files.map((file) => {
      const linkText = `![[${file.path}]]`;
      return `${linkText}`;
    });
    return `### Audio Sources

${links.join("\n\n")}`;
  }
  isAudioFile(file) {
    const validExtensions = ["mp3", "m4a", "wav", "webm", "ogg"];
    return validExtensions.includes(file.extension.toLowerCase());
  }
  getSelectedAudioFiles() {
    const files = [];
    const fileExplorers = this.app.workspace.getLeavesOfType("file-explorer");
    if (fileExplorers.length > 0) {
      const fileExplorer = fileExplorers[0].view;
      if (fileExplorer && fileExplorer.tree) {
        const selectedItems = fileExplorer.tree.selectedDoms;
        if (selectedItems) {
          for (const item of selectedItems) {
            const file = item.file;
            if (file instanceof import_obsidian6.TFile && this.isAudioFile(file)) {
              files.push(file);
            }
          }
        }
      }
    }
    return files;
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
