/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// src/main.ts
var main_exports = {};
__export(main_exports, {
  default: () => VocalogPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian7 = require("obsidian");

// src/settings.ts
var import_obsidian = require("obsidian");
var DEFAULT_SETTINGS = {
  audioFolder: "Inbox/Voice",
  outputFolder: "",
  // 空字符串表示使用根目录
  dailyNoteFormat: "YYYY-MM-DD",
  sttApiUrl: "https://api.openai.com/v1/audio/transcriptions",
  sttApiKey: "",
  sttModel: "whisper-1",
  llmApiUrl: "https://api.deepseek.com/v1/chat/completions",
  llmApiKey: "",
  llmModel: "deepseek-chat",
  systemPrompt: `\u4F60\u662F\u4E00\u4E2A\u6781\u7B80\u4E3B\u4E49\u7684\u903B\u8F91\u5206\u6790\u5E08\u3002
\u4F60\u7684\u4EFB\u52A1\u662F\u5C06\u7528\u6237\u7684\u8BED\u97F3\u8F6C\u5F55\u6587\u672C\u8F6C\u5316\u4E3A**\u9AD8\u5BC6\u5EA6\u3001\u65E0\u5E9F\u8BDD**\u7684 Markdown \u65E5\u5FD7\u3002

### \u6838\u5FC3\u539F\u5219
1. **\u53BB\u566A**\uFF1A\u5254\u9664\u6240\u6709\u91CD\u590D\u5185\u5BB9\u548C\u65E0\u610F\u4E49\u7684\u611F\u53F9\u3002
2. **\u52A8\u6001\u6E32\u67D3**\uFF1A**\u4EC5\u5F53**\u7C7B\u522B\u4E0B\u6709\u5B9E\u8D28\u5185\u5BB9\u65F6\u624D\u663E\u793A\u8BE5\u6807\u9898\u3002\u5982\u679C\u67D0\u4E2A\u7C7B\u522B\u4E3A\u7A7A\uFF0C**\u7EDD\u5BF9\u4E0D\u8981**\u663E\u793A\u8BE5\u6807\u9898\u6216"\u65E0"\u5B57\u6837\u3002
3. **\u91D1\u53E5**\uFF1A\u90A3\u4E9B\u7B80\u5355\u53E3\u8BED\u5316\u7684\uFF0C\u4F46\u53C8\u6DF1\u5165\u4EBA\u5FC3\u7684\u91D1\u53E5\u5F80\u5F80\u662F\u6700\u80FD\u9610\u8FF0\u89C2\u70B9\u7684\uFF0C\u5982\u679C\u6709\u8FD9\u6837\u7684\u53E5\u5B50\uFF0C\u8BF7\u4FDD\u7559\u8BB0\u5F55\u3002

### \u5904\u7406\u903B\u8F91
\u8BF7\u6309\u4EE5\u4E0B\u903B\u8F91\u5904\u7406\u6587\u672C\uFF0C\u5E76\u4EC5\u8F93\u51FA\u6709\u5185\u5BB9\u7684\u6A21\u5757\uFF1A

**\u6A21\u5757 1\uFF1A\u{1F4C5}\u4ECA\u65E5\u6240\u505A**
*\u5224\u65AD\u6807\u51C6\uFF1A\u662F\u5426\u53EF\u4EE5\u660E\u786E\u770B\u51FA\u4ECA\u65E5\u6240\u505A\u9879\u76EE\uFF0C\u4F8B\u5982\u8BFB\u4E86\u90A3\u672C\u4E66\u7684\u4EC0\u4E48\u6545\u4E8B\uFF0C\u542C\u4E86\u4EC0\u4E48\u5185\u5BB9\u7684\u64AD\u5BA2\u3002*
*\u683C\u5F0F\uFF1A*
- [x ] [\u52A8\u8BCD] [\u5BF9\u8C61]

**\u6A21\u5757 2\uFF1A\u{1F4A1} \u6D1E\u5BDF\u4E0E\u7075\u611F (Insights)**
*\u5224\u65AD\u6807\u51C6\uFF1A\u662F\u5426\u5B58\u5728\u72EC\u7279\u7684\u89C2\u70B9\u3001\u53CD\u601D\u3001\u51B3\u7B56\u6216\u7075\u611F\uFF1F*
*\u683C\u5F0F\uFF1A*
- **\u5173\u952E\u8BCD**\uFF1A\u4E00\u53E5\u8BDD\u6838\u5FC3\u89C2\u70B9\uFF0C\u5173\u952E\u8BCD\u662F\u603B\u7ED3\u51DD\u7EC3\u7684\u7ED3\u679C\u3002

**\u6A21\u5757 3\uFF1A\u2705 \u5F85\u529E\u4E8B\u9879 (Actions)**
*\u5224\u65AD\u6807\u51C6\uFF1A\u662F\u5426\u5B58\u5728\u660E\u786E\u7684\u4EFB\u52A1\u3001\u4E0B\u4E00\u6B65\u884C\u52A8\u6216\u9700\u8981\u8DDF\u8FDB\u7684\u4E8B\u9879\uFF1F*
*\u683C\u5F0F\uFF1A*
- [ ] [\u52A8\u8BCD] [\u5BF9\u8C61]

### \u793A\u4F8B
\u8F93\u5165\uFF1A"\u8BB0\u5F97\u4E70\u725B\u5976\u3002"
\u8F93\u51FA\uFF1A
## \u2705 \u5F85\u529E\u4E8B\u9879
- [ ] \u8D2D\u4E70\u725B\u5976

(\u6CE8\u610F\uFF1A\u4E0D\u8981\u8F93\u51FA\u7A7A\u7684"\u4ECA\u65E5\u6240\u505A"\uFF0C"\u6D1E\u5BDF"\u548C"\u8BB0\u5F55"\u6A21\u5757)`
};
var VocalogSettingTab = class extends import_obsidian.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    new import_obsidian.Setting(containerEl).setHeading().setName("Vocalog settings");
    new import_obsidian.Setting(containerEl).setHeading().setName("Basic settings");
    new import_obsidian.Setting(containerEl).setName("Audio folder").setDesc("Folder path where audio recordings are stored").addText((text) => text.setPlaceholder("Path").setValue(this.plugin.settings.audioFolder).onChange(async (value) => {
      this.plugin.settings.audioFolder = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Output folder").setDesc("Folder where daily notes will be saved (leave empty for vault root)").addText((text) => text.setPlaceholder("Folder").setValue(this.plugin.settings.outputFolder).onChange(async (value) => {
      this.plugin.settings.outputFolder = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Daily note format").setDesc("Date format for daily notes (using moment.js format)").addText((text) => text.setPlaceholder("Format").setValue(this.plugin.settings.dailyNoteFormat).onChange(async (value) => {
      this.plugin.settings.dailyNoteFormat = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setHeading().setName("Speech-to-text settings");
    new import_obsidian.Setting(containerEl).setName("Speech-to-text API URL").setDesc("API endpoint for speech-to-text service").addText((text) => text.setPlaceholder("https://api.openai.com/v1/audio/transcriptions").setValue(this.plugin.settings.sttApiUrl).onChange(async (value) => {
      this.plugin.settings.sttApiUrl = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("Speech-to-text API key").setDesc("API key for authentication").addText((text) => {
      text.setPlaceholder("Enter your API key").setValue(this.plugin.settings.sttApiKey).onChange(async (value) => {
        this.plugin.settings.sttApiKey = value;
        await this.plugin.saveSettings();
      });
      text.inputEl.type = "password";
    });
    new import_obsidian.Setting(containerEl).setName("Speech-to-text model").setDesc("Model to use for transcription").addText((text) => text.setPlaceholder("Model").setValue(this.plugin.settings.sttModel).onChange(async (value) => {
      this.plugin.settings.sttModel = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setHeading().setName("AI summarization settings");
    new import_obsidian.Setting(containerEl).setName("AI API URL").setDesc("API endpoint for AI service").addText((text) => text.setPlaceholder("https://api.deepseek.com/v1/chat/completions").setValue(this.plugin.settings.llmApiUrl).onChange(async (value) => {
      this.plugin.settings.llmApiUrl = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("AI API key").setDesc("API key for authentication").addText((text) => {
      text.setPlaceholder("Enter your API key").setValue(this.plugin.settings.llmApiKey).onChange(async (value) => {
        this.plugin.settings.llmApiKey = value;
        await this.plugin.saveSettings();
      });
      text.inputEl.type = "password";
    });
    new import_obsidian.Setting(containerEl).setName("AI model").setDesc("Model to use for summarization").addText((text) => text.setPlaceholder("Model").setValue(this.plugin.settings.llmModel).onChange(async (value) => {
      this.plugin.settings.llmModel = value;
      await this.plugin.saveSettings();
    }));
    new import_obsidian.Setting(containerEl).setName("System prompt").setDesc("Prompt to guide the AI in generating summaries").addTextArea((text) => {
      text.setPlaceholder("Enter system prompt").setValue(this.plugin.settings.systemPrompt).onChange(async (value) => {
        this.plugin.settings.systemPrompt = value;
        await this.plugin.saveSettings();
      });
      text.inputEl.rows = 10;
      text.inputEl.cols = 50;
    });
  }
};

// src/fileRetrieval.ts
var import_obsidian2 = require("obsidian");
function getTodayAudioFiles(vault, audioFolder) {
  const todayStart = (0, import_obsidian2.moment)().startOf("day");
  const todayEnd = (0, import_obsidian2.moment)().endOf("day");
  return getAudioFilesByDateRange(vault, audioFolder, todayStart, todayEnd);
}
function getAudioFilesByDateRange(vault, audioFolder, startDate, endDate) {
  const allFiles = vault.getFiles();
  const audioFiles = allFiles.filter((file) => {
    const isInFolder = file.path.startsWith(audioFolder);
    const validExtensions = ["mp3", "m4a", "wav", "webm", "ogg"];
    const ext = file.extension.toLowerCase();
    const isValidExtension = validExtensions.includes(ext);
    const fileTime = (0, import_obsidian2.moment)(file.stat.ctime);
    const isInRange = fileTime.isBetween(startDate, endDate, null, "[]");
    return isInFolder && isValidExtension && isInRange;
  });
  audioFiles.sort((a, b) => a.stat.ctime - b.stat.ctime);
  return audioFiles;
}
function getAudioFilesByDate(vault, audioFolder, date) {
  const dayStart = date.clone().startOf("day");
  const dayEnd = date.clone().endOf("day");
  return getAudioFilesByDateRange(vault, audioFolder, dayStart, dayEnd);
}

// src/transcription.ts
var import_obsidian3 = require("obsidian");
async function transcribeAudio(audioData, fileName, settings) {
  const formData = new FormData();
  const extension = fileName.split(".").pop() || "m4a";
  const blob = new Blob([audioData], { type: `audio/${extension}` });
  formData.append("file", blob, fileName);
  formData.append("model", settings.sttModel);
  try {
    const response = await fetch(settings.sttApiUrl, {
      method: "POST",
      headers: {
        "Authorization": `Bearer ${settings.sttApiKey}`
      },
      body: formData
    });
    if (!response.ok) {
      const errorText = await response.text().catch(() => "Unknown error");
      throw new Error(`STT API failed: ${response.statusText} - ${errorText}`);
    }
    const result = await response.json();
    return result.text;
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : String(error);
    if (errorMessage.includes("Failed to fetch") || errorMessage.includes("network")) {
      throw new Error(`\u7F51\u7EDC\u9519\u8BEF\uFF1A\u65E0\u6CD5\u8FDE\u63A5\u5230 STT API\u3002\u8BF7\u68C0\u67E5\uFF1A
1. API URL \u662F\u5426\u6B63\u786E
2. \u7F51\u7EDC\u8FDE\u63A5\u662F\u5426\u6B63\u5E38
3. \u662F\u5426\u9700\u8981\u4EE3\u7406
\u539F\u59CB\u9519\u8BEF: ${errorMessage}`);
    }
    throw error;
  }
}
async function transcribeBatch(files, vault, settings, noticeCallback) {
  const results = [];
  for (let i = 0; i < files.length; i++) {
    const file = files[i];
    noticeCallback(`Transcribing ${i + 1}/${files.length}: ${file.name}`);
    try {
      const audioData = await vault.readBinary(file);
      const text = await transcribeAudio(audioData, file.name, settings);
      results.push({
        time: (0, import_obsidian3.moment)(file.stat.ctime).format("HH:mm"),
        text,
        success: true
      });
    } catch (error) {
      console.error(`Failed to transcribe ${file.name}:`, error);
      results.push({
        time: (0, import_obsidian3.moment)(file.stat.ctime).format("HH:mm"),
        text: "[Transcription Failed]",
        success: false
      });
    }
  }
  return results;
}

// src/summarization.ts
var import_obsidian4 = require("obsidian");
async function summarizeTranscripts(transcripts, settings) {
  var _a, _b, _c;
  const context = transcripts.map((t) => `[${t.time}] ${t.text}`).join("\n\n");
  const requestBody = {
    model: settings.llmModel,
    messages: [
      { role: "system", content: settings.systemPrompt },
      { role: "user", content: context }
    ],
    temperature: 0.7
  };
  try {
    const response = await (0, import_obsidian4.requestUrl)({
      url: settings.llmApiUrl,
      method: "POST",
      headers: {
        "Authorization": `Bearer ${settings.llmApiKey}`,
        "Content-Type": "application/json"
      },
      body: JSON.stringify(requestBody)
    });
    const result = response.json;
    return (_c = (_b = (_a = result.choices[0]) == null ? void 0 : _a.message) == null ? void 0 : _b.content) != null ? _c : "";
  } catch (error) {
    const errorMessage = error instanceof Error ? error.message : String(error);
    if (errorMessage.includes("Failed to fetch") || errorMessage.includes("network")) {
      throw new Error(`\u7F51\u7EDC\u9519\u8BEF\uFF1A\u65E0\u6CD5\u8FDE\u63A5\u5230 LLM API\u3002\u8BF7\u68C0\u67E5\uFF1A
1. API URL \u662F\u5426\u6B63\u786E
2. API Key \u662F\u5426\u6709\u6548
3. \u7F51\u7EDC\u8FDE\u63A5\u662F\u5426\u6B63\u5E38
\u539F\u59CB\u9519\u8BEF: ${errorMessage}`);
    }
    throw error;
  }
}

// src/journalWriter.ts
var import_obsidian5 = require("obsidian");
async function writeToJournal(content, settings, vault, targetDate) {
  const dateToUse = targetDate || (0, import_obsidian5.moment)();
  const fileName = dateToUse.format(settings.dailyNoteFormat) + ".md";
  const filePath = settings.outputFolder ? `${settings.outputFolder}/${fileName}` : fileName;
  if (settings.outputFolder) {
    const folderPath = settings.outputFolder;
    const folder = vault.getAbstractFileByPath(folderPath);
    if (!folder) {
      await vault.createFolder(folderPath).catch(() => {
      });
    }
  }
  let dailyNote = vault.getAbstractFileByPath(filePath);
  if (!dailyNote) {
    dailyNote = await vault.create(filePath, "");
  }
  if (!(dailyNote instanceof import_obsidian5.TFile)) {
    throw new Error("Daily note is not a file");
  }
  let existingContent = await vault.read(dailyNote);
  const newContent = existingContent.trimEnd() + "\n\n" + content + "\n";
  await vault.modify(dailyNote, newContent);
}

// src/calendarModal.ts
var import_obsidian6 = require("obsidian");
var CalendarModal = class extends import_obsidian6.Modal {
  constructor(app, onSubmit) {
    super(app);
    this.onSubmit = onSubmit;
    this.selectedDates = /* @__PURE__ */ new Set();
    import_obsidian6.moment.locale("zh-cn");
    this.currentMonth = (0, import_obsidian6.moment)().startOf("month");
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.addClass("vocalog-calendar-modal");
    contentEl.createEl("h2", { text: "\u9009\u62E9\u65E5\u671F" });
    this.createMonthNavigation(contentEl);
    this.calendarEl = contentEl.createDiv({ cls: "calendar-container" });
    this.renderCalendar();
    contentEl.createEl("h3", { text: "\u5FEB\u901F\u9009\u62E9" });
    const quickButtons = contentEl.createDiv({ cls: "date-quick-options" });
    const addButton = (text, dates) => {
      const btn = quickButtons.createEl("button", { text });
      btn.onclick = () => {
        dates.forEach((d) => this.selectedDates.add(d));
        this.renderCalendar();
        this.updateGenerateButton();
      };
    };
    addButton("\u4ECA\u5929", [(0, import_obsidian6.moment)().format("YYYY-MM-DD")]);
    addButton("\u6628\u5929", [(0, import_obsidian6.moment)().subtract(1, "day").format("YYYY-MM-DD")]);
    addButton("\u672C\u5468", this.getWeekDates((0, import_obsidian6.moment)()));
    addButton("\u6700\u8FD17\u5929", this.getLast7Days());
    const clearBtn = quickButtons.createEl("button", { text: "\u6E05\u7A7A", cls: "mod-warning" });
    clearBtn.onclick = () => {
      this.selectedDates.clear();
      this.renderCalendar();
      this.updateGenerateButton();
    };
    const buttonContainer = contentEl.createDiv({ cls: "modal-button-container" });
    const generateBtn = buttonContainer.createEl("button", {
      text: `\u751F\u6210 (${this.selectedDates.size})`,
      cls: "mod-cta"
    });
    generateBtn.setAttribute("id", "generate-btn");
    generateBtn.onclick = () => {
      if (this.selectedDates.size === 0) {
        return;
      }
      this.close();
      this.submit();
    };
    const cancelBtn = buttonContainer.createEl("button", { text: "\u53D6\u6D88" });
    cancelBtn.onclick = () => {
      this.close();
    };
  }
  createMonthNavigation(containerEl) {
    const nav = containerEl.createDiv({ cls: "calendar-nav" });
    const prevBtn = nav.createEl("button", { text: "\u25C0 \u4E0A\u6708", cls: "calendar-nav-btn" });
    prevBtn.onclick = () => {
      this.currentMonth.subtract(1, "month");
      this.renderCalendar();
    };
    const monthLabel = nav.createEl("span", {
      text: this.currentMonth.format("YYYY\u5E74 MM\u6708"),
      cls: "calendar-month-label"
    });
    monthLabel.setAttribute("id", "month-label");
    const nextBtn = nav.createEl("button", { text: "\u4E0B\u6708 \u25B6", cls: "calendar-nav-btn" });
    nextBtn.onclick = () => {
      this.currentMonth.add(1, "month");
      this.renderCalendar();
    };
  }
  renderCalendar() {
    this.calendarEl.empty();
    const monthLabel = document.getElementById("month-label");
    if (monthLabel) {
      monthLabel.textContent = this.currentMonth.format("YYYY\u5E74 MM\u6708");
    }
    const weekdays = ["\u65E5", "\u4E00", "\u4E8C", "\u4E09", "\u56DB", "\u4E94", "\u516D"];
    const headerRow = this.calendarEl.createDiv({ cls: "calendar-weekdays" });
    weekdays.forEach((day) => {
      headerRow.createEl("div", { text: day, cls: "calendar-weekday" });
    });
    const daysGrid = this.calendarEl.createDiv({ cls: "calendar-days" });
    const startOfMonth = this.currentMonth.clone().startOf("month");
    const endOfMonth = this.currentMonth.clone().endOf("month");
    const firstDayOfWeek = startOfMonth.day();
    const startDate = startOfMonth.clone().subtract(firstDayOfWeek, "days");
    const lastDayOfWeek = endOfMonth.day();
    const endDate = endOfMonth.clone().add(6 - lastDayOfWeek, "days");
    const today = (0, import_obsidian6.moment)().format("YYYY-MM-DD");
    let currentDate = startDate.clone();
    while (currentDate.isSameOrBefore(endDate, "day")) {
      const dateStr = currentDate.format("YYYY-MM-DD");
      const dayEl = daysGrid.createEl("div", { cls: "calendar-day" });
      if (!currentDate.isSame(this.currentMonth, "month")) {
        dayEl.addClass("other-month");
      }
      if (currentDate.format("YYYY-MM-DD") === today) {
        dayEl.addClass("today");
      }
      if (this.selectedDates.has(dateStr)) {
        dayEl.addClass("selected");
      }
      if (currentDate.isAfter((0, import_obsidian6.moment)(), "day")) {
        dayEl.addClass("future");
      }
      dayEl.createEl("span", { text: currentDate.format("D") });
      dayEl.onclick = () => {
        if (this.selectedDates.has(dateStr)) {
          this.selectedDates.delete(dateStr);
        } else {
          this.selectedDates.add(dateStr);
        }
        this.renderCalendar();
        this.updateGenerateButton();
      };
      currentDate.add(1, "day");
    }
  }
  updateGenerateButton() {
    const btn = document.getElementById("generate-btn");
    if (btn) {
      btn.textContent = `\u751F\u6210 (${this.selectedDates.size})`;
    }
  }
  getWeekDates(date) {
    const dayOfWeek = date.day();
    const start = date.clone().subtract(dayOfWeek, "days");
    const dates = [];
    for (let i = 0; i < 7; i++) {
      dates.push(start.clone().add(i, "days").format("YYYY-MM-DD"));
    }
    return dates;
  }
  getLast7Days() {
    const dates = [];
    for (let i = 0; i < 7; i++) {
      dates.push((0, import_obsidian6.moment)().subtract(i, "days").format("YYYY-MM-DD"));
    }
    return dates;
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
  submit() {
    const dates = Array.from(this.selectedDates).map((d) => (0, import_obsidian6.moment)(d, "YYYY-MM-DD")).sort((a, b) => a.valueOf() - b.valueOf());
    this.onSubmit(dates);
  }
};

// src/main.ts
var VocalogPlugin = class extends import_obsidian7.Plugin {
  async onload() {
    await this.loadSettings();
    this.addSettingTab(new VocalogSettingTab(this.app, this));
    this.addRibbonIcon("microphone", "Vocalog: generate audio notes", async (evt) => {
      await this.generateAudioNotes();
    });
    this.addCommand({
      id: "generate-audio-notes",
      name: "Generate audio notes",
      callback: () => void this.generateAudioNotes()
    });
    this.addCommand({
      id: "generate-from-selected",
      name: "Generate from selected audio files",
      checkCallback: (checking) => {
        const files = this.getSelectedAudioFiles();
        if (files.length > 0) {
          if (!checking) {
            void this.generateFromFiles(files);
          }
          return true;
        }
        return false;
      }
    });
    this.addCommand({
      id: "generate-by-date-range",
      name: "Generate audio notes by date range",
      callback: () => {
        new CalendarModal(this.app, (dates) => {
          void this.generateBySelectedDates(dates);
        }).open();
      }
    });
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file) => {
        if (this.isAudioFile(file)) {
          menu.addItem((item) => {
            item.setTitle("Generate audio note").setIcon("microphone").onClick(async () => {
              await this.generateFromFiles([file]);
            });
          });
        }
      })
    );
  }
  async generateAudioNotes() {
    const notice = new import_obsidian7.Notice("Starting vocalog processing...", 0);
    try {
      const files = getTodayAudioFiles(this.app.vault, this.settings.audioFolder);
      if (files.length === 0) {
        notice.hide();
        new import_obsidian7.Notice("No audio recordings found for today.");
        return;
      }
      await this.processAudioFiles(files, notice);
    } catch (error) {
      notice.hide();
      console.error("Vocalog processing failed:", error);
      const errorMessage = error instanceof Error ? error.message : String(error);
      new import_obsidian7.Notice(`Error: ${errorMessage}`);
    }
  }
  async generateFromFiles(files, targetDate) {
    const notice = new import_obsidian7.Notice("Processing selected audio files...", 0);
    try {
      if (files.length === 0) {
        notice.hide();
        new import_obsidian7.Notice("No audio files selected.");
        return;
      }
      files.sort((a, b) => a.stat.ctime - b.stat.ctime);
      await this.processAudioFiles(files, notice, targetDate);
    } catch (error) {
      notice.hide();
      console.error("Audio processing failed:", error);
      const errorMessage = error instanceof Error ? error.message : String(error);
      new import_obsidian7.Notice(`\u274C Error: ${errorMessage}`);
    }
  }
  async generateBySelectedDates(dates) {
    const notice = new import_obsidian7.Notice("Processing audio files for selected dates...", 0);
    try {
      if (dates.length === 0) {
        notice.hide();
        new import_obsidian7.Notice("No dates selected.");
        return;
      }
      let totalProcessed = 0;
      for (const date of dates) {
        const files = getAudioFilesByDate(this.app.vault, this.settings.audioFolder, date);
        if (files.length > 0) {
          notice.setMessage(`Processing ${date.format("YYYY-MM-DD")} (${files.length} files)...`);
          await this.processAudioFiles(files, notice, date);
          totalProcessed += files.length;
        }
      }
      notice.hide();
      if (totalProcessed === 0) {
        new import_obsidian7.Notice(`No audio recordings found for selected dates.`);
      } else {
        new import_obsidian7.Notice(`\u2705 Processed ${totalProcessed} audio files from ${dates.length} day(s)!`);
      }
    } catch (error) {
      notice.hide();
      console.error("Selected dates processing failed:", error);
      const errorMessage = error instanceof Error ? error.message : String(error);
      new import_obsidian7.Notice(`\u274C Error: ${errorMessage}`);
    }
  }
  async generateByDateRange(startDate, endDate) {
    const notice = new import_obsidian7.Notice("Processing audio files by date range...", 0);
    try {
      if (startDate.isSame(endDate, "day")) {
        const files = getAudioFilesByDate(this.app.vault, this.settings.audioFolder, startDate);
        if (files.length === 0) {
          notice.hide();
          new import_obsidian7.Notice(`No audio recordings found for ${startDate.format("YYYY-MM-DD")}.`);
          return;
        }
        await this.processAudioFiles(files, notice, startDate);
      } else {
        const daysDiff = endDate.diff(startDate, "days") + 1;
        let totalProcessed = 0;
        for (let i = 0; i < daysDiff; i++) {
          const currentDate = startDate.clone().add(i, "days");
          const files = getAudioFilesByDate(this.app.vault, this.settings.audioFolder, currentDate);
          if (files.length > 0) {
            notice.setMessage(`Processing ${currentDate.format("YYYY-MM-DD")} (${files.length} files)...`);
            await this.processAudioFiles(files, notice, currentDate);
            totalProcessed += files.length;
          }
        }
        notice.hide();
        if (totalProcessed === 0) {
          new import_obsidian7.Notice(`No audio recordings found in date range.`);
        } else {
          new import_obsidian7.Notice(`\u2705 Processed ${totalProcessed} audio files from ${daysDiff} days!`);
        }
        return;
      }
    } catch (error) {
      notice.hide();
      console.error("Date range processing failed:", error);
      const errorMessage = error instanceof Error ? error.message : String(error);
      new import_obsidian7.Notice(`\u274C Error: ${errorMessage}`);
    }
  }
  async processAudioFiles(files, notice, targetDate) {
    notice.setMessage(`Found ${files.length} audio files. Transcribing...`);
    const transcripts = await transcribeBatch(
      files,
      this.app.vault,
      this.settings,
      (msg) => notice.setMessage(msg)
    );
    notice.setMessage("Generating summary with AI...");
    let finalContent;
    try {
      finalContent = await summarizeTranscripts(transcripts, this.settings);
    } catch (error) {
      console.error("LLM summarization failed:", error);
      finalContent = transcripts.map((t) => `[${t.time}] ${t.text}`).join("\n\n");
      finalContent = "\u26A0\uFE0F AI Summary Failed - Raw Transcripts:\n\n" + finalContent;
    }
    const audioLinks = this.generateAudioLinks(files);
    if (audioLinks) {
      finalContent += "\n\n---\n\n" + audioLinks;
    }
    notice.setMessage("Writing to daily note...");
    await writeToJournal(finalContent, this.settings, this.app.vault, targetDate);
    notice.hide();
    new import_obsidian7.Notice("Vocalog generated successfully!");
  }
  generateAudioLinks(files) {
    if (files.length === 0)
      return "";
    const links = files.map((file) => {
      const linkText = `![[${file.path}]]`;
      return `${linkText}`;
    });
    return `### Audio sources

${links.join("\n\n")}`;
  }
  isAudioFile(file) {
    const validExtensions = ["mp3", "m4a", "wav", "webm", "ogg"];
    return validExtensions.includes(file.extension.toLowerCase());
  }
  getSelectedAudioFiles() {
    const files = [];
    const fileExplorers = this.app.workspace.getLeavesOfType("file-explorer");
    if (fileExplorers.length > 0) {
      const fileExplorer = fileExplorers[0].view;
      if (fileExplorer == null ? void 0 : fileExplorer.tree) {
        const selectedItems = fileExplorer.tree.selectedDoms;
        if (selectedItems) {
          for (const item of selectedItems) {
            const file = item.file;
            if (file && this.isAudioFile(file)) {
              files.push(file);
            }
          }
        }
      }
    }
    return files;
  }
  async loadSettings() {
    this.settings = Object.assign({}, DEFAULT_SETTINGS, await this.loadData());
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
};
